services:
  postgres:
    image: postgres:17.5-alpine
    container_name: postgres_todo_server
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=test_user
      - POSTGRES_DB=todos
