http://localhost:3000

###

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "email": "12345@test.com",
  "password": "password123"
}

###
# @name login

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "no@test.com",
  "password": "password123"
}

###
GET http://localhost:3000/api/auth/protected/me
Cookie: {{login.response.headers.Set-Cookie}}

###
POST http://localhost:3000/api/protected/todos
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

{
  "title": "find lost treasure",
  "description": "This is a test todo item",
  "completed": false
}

###
GET http://localhost:3000/api/protected/todos
Cookie: {{login.response.headers.Set-Cookie}}