http://localhost:3000

### Signup

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "name": "Cheetara",
  "email": "no@test.com",
  "password": "password123"
}

###
# @name login

POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
  "email": "no@test.com",
  "password": "password123"
}

###
GET http://localhost:3000/api/auth/protected/me
Cookie: {{login.response.headers.Set-Cookie}}

### Make Todo
POST http://localhost:3000/api/protected/todos
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

{
  "title": "find lost treasure",
  "description": "This is a test todo item",
  "completed": false
}

### Get all todos for a user
GET http://localhost:3000/api/protected/todos
Cookie: {{login.response.headers.Set-Cookie}}

### Update a todo
PATCH http://localhost:3000/api/protected/todos/4f70a63d-f619-4371-ec22-b5429d28ac90
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

{
  "title": "find lost treasure",
  "description": "in the basement",
  "completed": true
}